apiVersion: v2
name: homework6
description: A Helm chart for Kubernetes

type: application

version: 1.0.0

appVersion: "1.0.0"

dependencies:
  - name: mysql
    version: "11.1.15"
    repository: https://charts.bitnami.com/bitnami