apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-homework8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-prometheus-exporter
          image: nginx/nginx-prometheus-exporter:1.3.0
          args: [ "--nginx.scrape-uri=http://localhost:80/metrics" ]
          ports:
            - containerPort: 9113
              name: http
        - name: web-server
          image: nginx
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/status.conf
              subPath: status.conf
      volumes:
      - name: config-volume
        configMap:
          name: cm-homework8
---
apiVersion: v1
kind: Service
metadata:
  name: svc-homework8
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: metrics
    - port: 9113
      targetPort: 9113
      name: exporter
  selector:
    app: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-homework8
data:
  status.conf: |-
    server {
      listen 8080;

      location /metrics {
        stub_status;
      }

    }