apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-homework5
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: monitoring
      containers:
      - name: web-server
        image: custom-nginx:1.0.0-SNAPSHOT
        volumeMounts:
        - name: workdir
          mountPath: /homework
        - name: cm-volume
          mountPath: "/homework/conf"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "rm /homework/index.html" ]
      initContainers:
      - name: busybox-container
        image: busybox:1.28
        command: [ "/bin/sh", "-c" ]
        args: [ 'curl --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt --header "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" -X GET https://kubernetes.default.svc/metrics -o /init/metrics.html' ]
      - name: busybox-container
        image: busybox:1.28
        command:
        - wget
        - "-O"
        - "/init/index.html"
        - https://otus.ru
        volumeMounts:
        - name: workdir
          mountPath: "/init"
      volumes:
        - name: workdir
          persistentVolumeClaim:
            claimName: pvc2-homework4
        - name: cm-volume
          configMap:
            name: cm-homework4
