apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-homework5
  namespace: homework
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-homework5
