apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework2
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: web-server
        image: custom-nginx:1.0.0-SNAPSHOT
        volumeMounts:
        - name: workdir
          mountPath: /homework
        readinessProbe:
          exec:
            command: ["/bin/sh", "-c", "test -e /homework/index.html" ]
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "rm /homework/index.html" ]
      initContainers:
      - name: busybox-container
        image: busybox:1.28
        command:
        - wget
        - "-O"
        - "/init/index.html"
        - https://otus.ru
        volumeMounts:
        - name: workdir
          mountPath: "/init"
      volumes:
      - name: workdir
        emptyDir: {}
