{{range .Values.roles }}
{{if .create}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .type }}
metadata:
  name: {{.name}}
  namespace: {{.namespace}}
rules:
{{ range .rules }}- {{toYaml . | nindent 2 }}{{ end }}

{{ end }}
{{ end }}