{{range .Values.serviceAccounts }}
{{if .createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.name}}-sa-secret
  namespace: {{.namespace}}
  annotations:
    kubernetes.io/service-account.name: {{ .name}}
type: kubernetes.io/service-account-token
{{ end }}
{{ end }}
