{{ if .Values.storageclass.create }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: {{ .Values.storageclass.provisioner}}
reclaimPolicy: {{ .Values.storageclass.reclaimPolicy}}
volumeBindingMode: {{ .Values.storageclass.volumeBindingMode}}

{{ end }}