apiVersion: v1
kind: Pod
metadata:
  name: homework1
  namespace: homework
spec:
  containers:
  - name: web-server
    image: custom-nginx:1.0.0-SNAPSHOT
    volumeMounts:
    - name: workdir
      mountPath: /homework
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "rm /homework/index.html" ]
  initContainers:
  - name: busybox-container
    image: busybox:1.28
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - https://otus.ru
    volumeMounts:
    - name: workdir
      mountPath: "/init"
  volumes:
  - name: workdir
    emptyDir: {}
